name: Swift

on: [push]

jobs:
  build:

    container: 
      image: vapor/swift:5.1-xenial
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
